### ISSUE TITLE
Debugging in VSC doesn't start

### ISSUE THREAD

**Issue by GlebBazhanov** [SketchUp/sketchup-ruby-api-tutorials#11]
[Debug Configuration](https://github.com/SketchUp/sketchup-ruby-api-tutorials/wiki/VSCode-Debugger-Setup#debug-configuration)

There is not an error but debugging does not started, because folder "/src" does not exist by default.
"cwd": "${workspaceRoot}/src"
"remoteWorkspaceRoot": "${workspaceRoot}/src"

**Comment by thomthom** [comment]
You would have to adjust that to fit your own project's filestructure.

**Comment by thomthom** [comment]
I removed the `/src` part from the guide - it wasn't needed.
