### ISSUE TITLE
rubymine not work.

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/sketchup-ruby-api-tutorials#13]
## rubymine can start sketchup,but it can't connect the port of debug.BreakPoint doesn't work.
![1](https://user-images.githubusercontent.com/28385638/38982318-2207b248-43f4-11e8-9374-14a2396f03b9.jpg)
![2](https://user-images.githubusercontent.com/28385638/38982319-22382c0c-43f4-11e8-8e9b-64b4f4d01f5a.jpg)
![3](https://user-images.githubusercontent.com/28385638/38982321-22676c1a-43f4-11e8-9888-9319137b0c84.jpg)
![4](https://user-images.githubusercontent.com/28385638/38982468-84d5f452-43f4-11e8-81bc-56e434a1a4f8.jpg)
![5](https://user-images.githubusercontent.com/28385638/38982472-85054234-43f4-11e8-81e9-3f46aa551f96.jpg)
![6](https://user-images.githubusercontent.com/28385638/38982646-fbc9b6a2-43f4-11e8-9c74-b1562828c8c3.jpg)

**Comment by thomthom** [comment]
Are you using the first release of RubyMine 2018? If so, make sure to update it, because it had a bug that caused remote debugging to fail: https://forums.sketchup.com/t/rubymine-debug-error-sketchup-pro-2018/65359

**Comment by thomthom** [comment]
Also, did you add the debugger DLL in the SketchUp application directory?

**Comment by LItterBoy-GB** [comment]
@thomthom  I add the  debugger DLL. I see the [solution](https://forums.sketchup.com/t/rubymine-debug-error-sketchup-pro-2018/65359)

**Comment by LItterBoy-GB** [comment]
@thomthom  Sketchup  doesn't load Testup-2, so breakpoint doesn't work.  I changed the RubyMine to 2017.3

**Comment by thomthom** [comment]
I'm not clear to what your actual question is right now.

> Sketchup doesn't load Testup-2, so breakpoint doesn't work.

You say SketchUp doesn't load TestUp? You are getting errors?
Or did you not set it up to load? RubyMine will not load the extension for you - that you have to do yourself.

>  I changed the RubyMine to 2017.3
Changed it from what? Did changing it solve your issue?

**Comment by LItterBoy-GB** [comment]
@thomthom  How can rubymine load the testup-2?
I debug, the rubymine connect debug_port of sketchup, but I don't find "testup-2" in plugins of sketchup.

**Comment by thomthom** [comment]
You have to set up TestUp to load yourself.

What I do is create a file in the Plugins directory that adds the location of TestUp to the load path and then require it.

Something like:

```ruby
# For extension development only. Load extension from source control:
$LOAD_PATH << 'C:/Users/Username/Source/TestUp2/src'
Sketchup.require 'testup.rb'
```

**Comment by LItterBoy-GB** [comment]
@thomthom  Is it necessary to debug my program? I thought it (click the debug button) would be enough.

**Comment by LItterBoy-GB** [comment]
@thomthom 
## You say SketchUp doesn't load TestUp? 
Yes.RubyMine can start Sketchup,But I don't find the program in Sketchup
## You are getting errors?
No error.
## did you not set it up to load? 
How do I load it?

# Thank you very much for your patience.

**Comment by LItterBoy-GB** [comment]
@thomthom Thank you very much.It work.I thought I didn't need to load the file.

**Comment by thomthom** [comment]
We'll try to improve the debugger setup guide.

**Comment by DanRathbun** [comment]
@thomthom Please close this issue, or move it to the appropriate repo (Debugger or TestUp,) as it is not a tutorials issue.
