### ISSUE TITLE
VSCode task.json - & was unexpected at this time.

### ISSUE THREAD

**Issue by asouth** [SketchUp/sketchup-ruby-api-tutorials#14]
Hi,

There maybe a simple fix for this but as far as I can tell I followed the instructions [here](https://github.com/SketchUp/sketchup-ruby-api-tutorials/wiki/VSCode-Debugger-Setup) for setting the VSCode environment up for debugging ruby extensions for Sketchup 2016 to the letter.

However with Sketchup closed, when I choose [Tasks -> Run Tasks -> Debug Sketchup 2016] I get the following message in the Terminal:

> Executing task: &'C:/Program Files/SketchUp/SketchUp 2016/SketchUp.exe' -rdebug 'ide port=7000' <
>
> & was unexpected at this time.
> The terminal process terminated with exit code: 1

It seems to be complaining about  the & in front of the filepath, but if i remove it just complains about the C:

Can anyone assist with this?

Thanks
Alex

**Comment by asouth** [comment]
apologies i just realised i posted this in the wrong section.

**Comment by thomthom** [comment]
For the record, conversation continues at https://github.com/SketchUp/sketchup-ruby-debugger/issues/18
