### ISSUE TITLE
how to write a sketchup plugin?

### ISSUE THREAD

**Issue by Zwe1** [SketchUp/sketchup-ruby-api-tutorials#17]
help! !
if there is somebody can tell me how to make a sketchup plugin, I wanna enhance the function of sketchup, especially on exporting behavior.
thanks and all !!!

**Comment by thomthom** [comment]
I would recommend starting a thread in the Developers section of our user forums:
https://forums.sketchup.com/c/developers/12

Start by explaining what you want to do. What you have done so far and what you are stuck with.
