### ISSUE TITLE
task.json issue for vs code

### ISSUE THREAD

**Issue by zhanhaikun** [SketchUp/sketchup-ruby-api-tutorials#18]
Hi, I've tried to set task.json as below, but it doesn't work.
`{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Debug SketchUp 2019",
        "type": "shell",
        "command": "open -a '/Applications/SketchUp 2019/SketchUp.app' --args -rdebug 'ide port=7000'",
        "windows": {
          "command": "&'C:/Program Files/SketchUp/SketchUp 2019/SketchUp.exe' -rdebug 'ide port=7000'"
        }
      }
    ]
  }`

The TERMINAL prompts the error:
`Executing task: &'C:/Program Files/SketchUp/SketchUp 2019/SketchUp.exe' -rdebug 'ide port=7000' <

& was unexpected at this time.
The terminal process terminated with exit code: 1`

I remove the '&' or change the '/' to '\\'， still not make any sense.
I really need your help!

**Comment by thomthom** [comment]
Did you resolve your issue?
