### ISSUE TITLE
empty group entity becomes deleted entity after pushpull a face

### ISSUE THREAD

**Issue by nanangqq** [SketchUp/sketchup-ruby-api-tutorials#21]
hello, sketchup.

I sometimes use sketchup ruby api.

When I tried to access an empty group after pushpull a face in active_model.active_entities, I couldn't access the group because it already has deleted. Sketchup::Face.pushpull method only deletes empty groups in active_model.active_entities.

I can use non-empty-group to avoid this issue, but I just want to know the reason why pushpull destroys empty groups.

thank you.

**Comment by Eneroth3** [comment]
Hi,

SketchUp automatically purges empty groups. You can wait to create a group until you draw something in it.

**Comment by nanangqq** [comment]
Thank you for answer!
