### ISSUE TITLE
README typo in Using way (2)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/sketchup-ruby-api-tutorials#3]
README typo in Using way (2), viz:
_section_
**How Do I Use These Tutorials?**

2. ... Get the code right on your machine, **will** all the comments for easy access.
_should be:_
2. ... Get the code right on your machine, **with** all the comments for easy access.

-----
This error also propagated to the online introduction, at:
http://developer.sketchup.com/en/content/tutorials

**Comment by DanRathbun** [comment]
FIXED (Commit: https://github.com/SketchUp/sketchup-ruby-api-tutorials/commit/ded0c896f61cc035485c0920dd2b7937f14e2391) - Closing

The page at:
https://developer.sketchup.com/developers/example-extensions
... is still incorrect **but** as the webpage is outside the scope of this repository and (apparently) outside the control of the extensibility team, I'll cease opening issues here for the website.

**Comment by thomthom** [comment]
We should be able to fix those pages.

**Comment by thomthom** [comment]
Ah, we would be better using the issue tracker repo for this.
